---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "requirements/ansible"
    schedule:
      interval: "daily"
    groups:
      ansible:
        patterns:
          - "ansible-*"
        update-types:
          - "patch"
      others:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "requirements/piptools"
    schedule:
      interval: "daily"
    groups:
      piptools:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
