---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "requirements/ansible"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Rome"
    ignore:
      - dependency-name: "ansible-*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    groups:
      ansible:
        patterns:
          - "ansible-*"
        update-types:
          - "patch"
  - package-ecosystem: "pip"
    directory: "requirements/pip"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Rome"
    groups:
      pip:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "requirements/local"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Rome"
    groups:
      local:
        patterns:
          - "*"
        exclude-patterns:
          - "yt-dlp"   # no semver
        update-types:
          - "minor"
          - "patch"
