---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "requirements/ansible"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "ansible-*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    groups:
      ansible:
        patterns:
          - "ansible-*"
        update-types:
          - "patch"
      others:
        patterns:
          - "*"
        exclude-patterns:
          - "ansible-*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "requirements/piptools"
    schedule:
      interval: "daily"
    groups:
      piptools:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "requirements/local"
    schedule:
      interval: "daily"
    groups:
      local:
        patterns:
          - "*"
        exclude-patterns:
          - "yt-dlp" # no semver
        update-types:
          - "minor"
          - "patch"
