---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "requirements/"
    schedule:
      interval: "daily"
    groups:
      ansible:
        patterns:
          - "ansible-*"
        update-types:
          - "patch"
      piptools:
        patterns:
          - "build"
          - "packaging"
          - "pip-tools"
          - "pyproject-hooks"
          - "wheel"
        update-types:
          - "minor"
          - "patch"
      others:
        patterns:
          - "*"
